{% set name = "conda-auth" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda-incubator/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: a510cf0f24068905f1cc620cc11c50928ec207d66b1db42254522f521f7c42e8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.8.1,<4.0.0
    - click
    - conda >=23.9.0
    - keyring
    - requests
    - ruamel.yaml

test:
  imports:
    - conda_auth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/conda-incubator/conda-auth
  summary: Conda plugin for improved access to private channels
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - travishathaway
    - jezdez
